DistinctCodes/AssetsUp

- backend/src/app.module.ts
- backend/src/notifications/notification-template.entity.ts
- backend/src/notifications/notification.entity.ts
Notification and NotificationTemplate entities.
Service for CRUD, querying, and mock email (nodemailer) support.
Controller for managing templates and user notifications.
Module is imported in [app.module.ts](vscode-file://vscode-app/c:/Users/Surface/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) for use across the backend.
> implement standalone notification module

- backend/src/app.module.ts
- backend/src/status-history/dto/create-status-history.dto.ts
- backend/src/status-history/entities/status-history.entity.ts
- backend/src/status-history/status-history.controller.ts
- backend/src/status-history/status-history.e2e-spec.ts
- backend/src/status-history/status-history.module.ts
- backend/src/status-history/status-history.service.spec.ts
- backend/src/status-history/status-history.service.ts
closes #103 
Summary
Adds an isolated status-history module to record and query asset status transitions over time, independent of the Asset module.
Scope
Independent storage for status history with a mock assetId (no FK).
Consistent status values via AssetStatus enum.
Endpoints to log and fetch status changes.
Changes
Entity and enums:
backend/src/status-history/entities/status-history.entity.ts
StatusHistory
fields: assetId, previousStatus, newStatus, changeDate, changedBy.
AssetStatus enum: active, under_maintenance, in_transfer, disposed.
Indices on assetId, changeDate.
DTOs:
backend/src/status-history/dto/create-status-history.dto.ts
Service:
backend/src/status-history/status-history.service.ts
logStatusChange(dto)
getByAsset(assetId)
Controller: …
> feat(status-history): standalone module to track asset status changes

- backend/src/inventory/entities/inventory-item.entity.ts
- backend/src/inventory/inventory-alerts/inventory-alerts.controller.ts
- backend/src/inventory/inventory-alerts/inventory-alerts.module.ts
- backend/src/inventory/inventory-alerts/inventory-alerts.service.ts
- backend/src/inventory/inventory-alerts/listeners/inventory.listener.ts
**Closes #223**
This pull request introduces a new **`InventoryAlertsModule`** to proactively monitor and report on low stock levels. The system automatically generates alerts when an item's quantity drops below its predefined threshold, enabling timely reordering and preventing stockouts.
The implementation uses a decoupled, event-driven architecture. The core logic listens for `inventory.stock.changed` events, triggering a threshold check automatically after any stock movement without creating tight coupling with the main inventory management service.
-   **`InventoryItem` Entity Update**: The `InventoryItem` entity has been updated with a new `threshold` field to store the reorder point for each item.
-   **`InventoryAlertsService`**: This service contains the primary logic for:
- …
> feat(inventory): implement inventory threshold alerts module

- backend/inventory-items/dto/create-inventory-item.dto.ts
- backend/inventory-items/entities/inventory-item.entity.ts
- backend/inventory-items/inventory-items.controller.ts
- backend/inventory-items/inventory-items.module.ts
- backend/inventory-items/inventory-items.service.ts
**Closes #225**
This pull request introduces the foundational **`InventoryItemsModule`**, which provides the core CRUD (Create, Read, Update, Delete) functionality for managing consumable stock items in the application.
This module establishes the `inventory_items` table and the necessary services and controllers to create new stock items (e.g., stationery, spare parts) and track their quantities. Crucially, it is designed to be the central source of truth for inventory data and is built to seamlessly integrate with other modules, such as stock movements and threshold alerts, via an event-driven approach.
---
-   **`InventoryItem` Entity**: A new TypeORM entity that defines the `inventory_items` table with columns for `name`, `quantity`, and `reorderLevel`.
- …
> feat(inventory): implement inventory stock items module

- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/asset-categories/asset-category.entity.ts
- backend/src/asset-subcategories/asset-subcategories.controller.ts
- backend/src/asset-subcategories/asset-subcategories.module.ts
- backend/src/asset-subcategories/asset-subcategories.service.ts
- backend/src/asset-subcategories/dto/create-asset-subcategory.dto.ts
- backend/src/asset-subcategories/dto/update-asset-subcategory.dto.ts
- backend/src/asset-subcategories/entities/asset-subcategory.entity.ts
- backend/src/inventory/entities/inventory-item.entity.ts
Closes #234
- Implements asset subcategories for more detailed classification (e.g., IT Equipment → Laptops → Dell).
- Adds `asset_subcategories` table with `id`, `name`, and `parentCategoryId`.
- Provides CRUD APIs for asset subcategories.
- Links assets (inventory items) to subcategories.
- Generated `asset-subcategories` NestJS module.
- Defined `AssetSubcategory` entity and DTOs (`create`, `update`).
- Implemented service and controller for CRUD operations.
- Updated asset entity to reference subcategory.
- Enables hierarchical asset categorization.
- Assets can now be linked to specific subcategories for improved organization and reporting.
> implemented Asset Subcategory Module

- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/suppliers/dto/create-supplier.dto.ts
- backend/src/suppliers/dto/update-supplier.dto.ts
- backend/src/suppliers/entities/supplier.entity.ts
- backend/src/suppliers/suppliers.controller.ts
- backend/src/suppliers/suppliers.module.ts
- backend/src/suppliers/suppliers.service.ts
This PR entails :
1. Generated suppliers module.
2. A well Defined entity & DTOs.
3. Service logics  & controller endpoints.
closes #227
> Implemented Supplier Module

- backend/src/dashboard/dashboard.controller.ts
- backend/src/dashboard/dashboard.module.ts
- backend/src/dashboard/dashboard.services.ts
- backend/src/dashboard/dto/dashboard-metrics.dto.ts
**Closes #217**
This pull request introduces a new **`DashboardModule`** to provide high-level, summarized statistics for the application's main dashboard. It exposes a single, optimized API endpoint that returns key metrics such as total assets, disposed assets, and current stock levels.
The core of this feature is built around efficient database aggregation queries using TypeORM's `QueryBuilder`. This ensures that the dashboard can load quickly without fetching and processing large datasets in the application layer, which is critical for performance.
---
-   **`DashboardService`**: Contains the primary business logic. The `getMetrics` method runs several database queries concurrently using `Promise.all` to efficiently calculate summary statistics.
-   **`DashboardController`**: Exposes …
> feat(dashboard): implement dashboard metrics module

- backend/licenses/dto/create-license.dto.ts
- backend/licenses/entities/license.entity.ts
- backend/licenses/licenses.controller.ts
- backend/licenses/licenses.module.ts
- backend/licenses/service/licenses.service.ts
- backend/licenses/tasks/license-expiry.task.ts
- backend/package-lock.json
- backend/package.json
**Closes #294**
This pull request introduces a new **`LicensesModule`** to track and manage compliance documents and licenses associated with assets (e.g., vehicle registrations, software licenses).
The core of this feature is a proactive alerting system. A scheduled job runs daily to automatically detect licenses that are nearing their expiration date and triggers an event to notify the relevant parties. This transforms compliance management from a reactive, manual process into an automated, proactive one.
-   **`License` Entity**: A new TypeORM entity that defines the `licenses` table. It stores the `assetId`, `licenseType`, `expiryDate`, a `documentUrl`, and an `isExpiryNotified` flag to prevent duplicate alerts.
-   **`LicensesService`**: Provides the core CRUD logic for managing …
> feat(compliance): implement license and compliance module

- frontend/components/ui/Breadcrumb.example.tsx
- frontend/components/ui/Breadcrumb.tsx
- frontend/components/ui/index.ts
Implements a basic breadcrumb navigation component as requested in #316.
- ✅ Created `Breadcrumb.tsx` component in `components/ui/`
- ✅ Accepts array of `{ label: string, href?: string }` items as props
- ✅ Renders links for all items except the last (plain text)
- ✅ Uses Tailwind classes: `flex`, `gap-2`, `text-sm`
- ✅ Fully reusable across multiple pages
- ✅ Added example usage demonstrations
Closes #316
> feat: implement basic breadcrumb navigation component

- contracts/assetsup/src/lib.rs
- contracts/assetsup/src/tests/asset.rs
- contracts/assetsup/src/tests/mod.rs
- contracts/assetsup/src/tests/types.rs
- contracts/assetsup/src/types.rs
The fix implements a comprehensive shared types system for the AssetsUp contracts, providing consistent and reusable enums across all contract modules with proper Soroban serialization support.
Features Added
- **`AssetType`** - Distinguishes between Physical and Digital assets
- **`AssetStatus`** - Tracks asset lifecycle (Active, InMaintenance, Disposed)  
- **`ActionType`** - Audit trail actions (Procured, Transferred, Maintained, Disposed, CheckedIn, CheckedOut)
- **`PlanType`** - Subscription tiers (Basic, Pro, Enterprise)
- **`SubscriptionStatus`** - Subscription states (Active, Expired, Cancelled)
Technical Implementation
- All enums use `#[contracttype]` for Soroban serialization
- Proper `#[derive(Clone, Debug, Eq, PartialEq)]` traits
- Comprehensive documentation with `///` …
> Fix: [CONTRACT] Implement Common Types Module

- frontend/lib/utils/buildQueryString.test.ts
- frontend/lib/utils/buildQueryString.ts
Adds a new utility buildQueryString to convert objects into URL query strings.
Supports nested objects, arrays, and special characters.
Ignores null/undefined values and returns an empty string for empty objects.
Fully type-safe (QueryValue) and tested with Jest.
> feat(utils): add buildQueryString utility (#307)

- frontend/components/ui/Button.tsx
Summary
Implements a fully-typed, reusable Button component in components/ui/Button.tsx to ensure consistent button styling across the application.
Changes
✅ Created components/ui/Button.tsx with TypeScript support
✅ Added variant prop: primary (blue) and secondary (gray)
✅ Added size prop: sm, md, lg
✅ Includes proper disabled state styling
✅ Extends native HTML button attributes for full flexibility
✅ Implements accessible focus states and smooth hover transitions
✅ Marked as Client Component with 'use client' directive for Next.js App Router compatibility
> feat: Create a Reusable Button Component

- frontend/lib/utils/formatDate.test.ts
- frontend/lib/utils/formatDate.ts
Implements a comprehensive date formatting utility function as requested in issue #308. The utility supports multiple date formats including short date (DD/MM/YYYY) and relative time formatting.
- **Short Format**: Uses `Intl.DateTimeFormat` to format dates as DD/MM/YYYY
- **Relative Format**: Uses `Intl.RelativeTimeFormat` to show relative time (e.g., "1 day ago", "in 2 hours")
- **TypeScript Support**: Full type definitions with `DateFormat` type
- **Error Handling**: Proper validation for invalid dates and unsupported formats
- **Comprehensive Testing**: 11 unit tests covering all scenarios
All tests are passing successfully:
**Test Summary:**
- ✅ **11 tests passed, 0 failed**
- ✅ **Short format tests**: 3/3 passed
- ✅ **Relative format tests**: 5/5 passed  
- ✅ **Error handling …
> Fix: FRONTEND: Date Formatter (Utility Function)

- backend/src/cargo/cargo.controller.ts
- backend/src/cargo/cargo.module.ts
- backend/src/cargo/cargo.service.ts
- backend/src/cargo/dto/create-cargo.dto.ts
- backend/src/cargo/entities/cargo.entity.ts
- backend/src/shipments/entities/shipment.entity.ts
**Closes #325**
This pull request introduces a new **`CargoModule`** to manage individual cargo items within a shipment. It provides the necessary data structure and API endpoints to create and retrieve item-specific details like description, weight, and value.
This feature establishes a one-to-many relationship between `Shipment` and `Cargo` entities, enabling a more granular level of tracking and data management, which is foundational for future features like customs declarations or item-specific insurance.
-   **`Cargo` Entity**: A new TypeOrm entity that defines the `cargo` table. It includes a `ManyToOne` relationship, linking each cargo item to a parent `Shipment`.
-   **`Shipment` Entity Update**: The `Shipment` entity has been updated with a `OneToMany` relationship to complete …
> feat(cargo): create cargo module to manage items within shipments

- frontend/app/not-found.tsx
This PR introduces a global 404 Not Found page for the application.
- Added `app/not-found.tsx` to handle invalid routes.
- The page displays a friendly "Page not found" message.
- Includes a link back to the homepage using `next/link`.
- Styled with basic Tailwind utilities (`flex`, `justify-center`, `text-lg`, etc.).
- Requires no extra design assets.
- Navigate to any non-existing route (e.g., `/random-page`).
- Confirm that the Not Found page is displayed with the correct message and a working link back to `/`.
Closes #318
> FRONTEND: Implement Not Found Page #318

- BRANCH_MODULE_IMPLEMENTATION_SUMMARY.md
- RBAC_IMPLEMENTATION_SUMMARY.md
- backend/src/assets/assets.controller.rbac.example.ts
- backend/src/assets/entities/assest.entity.ts
- backend/src/auth/auth.module.ts
- backend/src/auth/rbac.integration.spec.ts
- backend/src/auth/roles.decorator.spec.ts
- backend/src/auth/roles.decorator.ts
- backend/src/auth/roles.enum.spec.ts
- backend/src/auth/roles.enum.ts
- backend/src/auth/roles.guard.spec.ts
- backend/src/auth/roles.guard.ts
- backend/src/branches/branches.controller.ts
- backend/src/branches/branches.module.ts
- backend/src/branches/branches.service.comprehensive.spec.ts
- backend/src/branches/branches.service.ts
- backend/src/branches/entities/branch.entity.ts
- backend/src/departments/department.entity.ts
- backend/src/users/entities/user.entity.ts
Implemented Role-Based Access Control (RBAC) 
Description
opened [last week](https://github.com/DistinctCodes/AssetsUp/issues/239#issue-3459862746)
Collaborator
We need a roles guard system to restrict access to certain routes. For example:
Admin → Full access
Manager → Limited CRUD on assets
Employee → Read-only access to assigned assets
Expected Behavior:
Roles decorator (@Roles(‘admin’)).
Guard that checks roles before allowing route access.
Users linked with a role field.
Tasks:
Created roles enum (Admin, Manager, Employee).
Implemented custom RolesGuard.
Add @Roles() decorator.
Protect sensitive routes with RBAC.
closes[#239]
> Role based

- frontend/lib/utils/formatCurrency.test.ts
- frontend/lib/utils/formatCurrency.ts
- package-lock.json
This addresses issue #304 
- **`lib/utils/formatCurrency.ts`**
- Formats numbers as localized currency strings using `Intl.NumberFormat`
- Defaults to NGN (Nigerian Naira), falls back to USD for unsupported currencies
- Configurable options: currency code, locale, decimal places
- Full TypeScript type definitions
- **`lib/utils/formatCurrency.test.ts`**
- Tests: basic formatting and decimals
```typescript
formatCurrency(5000)              // "₦5,000.00"
formatCurrency(1200, "USD")       // "$1,200.00"
formatCurrency(999.99, "JPY")     // "¥999,99"
formatNaira(3000)                 // "₦3,000.00"
```
> feat: format currency utility

- backend/src/asset-locations/dto/assets.dto.ts
- backend/src/asset-locations/dto/branch.dto.ts
- backend/src/asset-locations/dto/location.dto.ts
- backend/src/asset-locations/entities/location.entity.ts
- backend/src/asset-locations/locations.controller.ts
- backend/src/asset-locations/locations.module.ts
- backend/src/asset-locations/locations.service.ts
> assets locations module implementation

- backend/src/insurance/insurance-query.dto.ts
- backend/src/insurance/insurance.controller.ts
- backend/src/insurance/insurance.dto.ts
- backend/src/insurance/insurance.entity.ts
- backend/src/insurance/insurance.module.ts
- backend/src/insurance/insurance.service.ts
- backend/src/insurance/notification.service.ts
- backend/src/insurance/update-insurance.dto.ts
> created the insurance module

- backend/src/cost-centers/cost-center.entity.ts
- backend/src/cost-centers/cost-centers.controller.ts
- backend/src/cost-centers/cost-centers.service.ts
- backend/src/cost-centers/cost.module.ts
- backend/src/cost-centers/create-cost-center.dto.ts
> cost center implementation module

- backend/src/app.module.ts
- backend/src/audit-logs/audit-logging.interceptor.ts
- backend/src/audit-logs/audit-logs.module.ts
- backend/src/audit-logs/audit-logs.service.ts
- backend/src/audit-logs/entities/audit-log.entity.ts
closes #222 
- Implemented an **audit logging system** to track all user actions (login, CRUD operations, asset transfers, etc.) for accountability and system transparency.
> implemented the audit log module

- frontend/app/layout.tsx
- frontend/components/CountdownTimer.tsx
- frontend/components/Hero.tsx
- frontend/components/Navbar.tsx
This PR delivers the Coming Soon landing page as outlined in the design specifications. It introduces modular and reusable Navbar and Hero components, along with a live CountdownTimer that updates in real-time. The page is styled using TailwindCSS, featuring animated gradient backgrounds, subtle floating blur effects, and glassmorphism for visual depth. It also includes responsive layout adjustments for all screen sizes and maintains consistency with the project’s TypeScript code standards. All design elements aim to closely match the original mockup with a focus on usability, responsiveness, and visual accuracy.
closes #364
> feat: add CountdownTimer component and integrate it into Hero section
