DistinctCodes/AssetsUp

frontend/.gitignore, frontend/app/branches/[id]/assets/loading.tsx, frontend/app/branches/[id]/assets/page.tsx, frontend/app/branches/[id]/edit/page.tsx, frontend/app/branches/[id]/page.tsx, frontend/app/branches/loading.tsx, frontend/app/branches/new/page.tsx, frontend/app/branches/page.tsx, frontend/app/error.tsx, frontend/app/loading.tsx, frontend/app/not-found.tsx, frontend/components/branches/branches/branch-form.tsx, frontend/package-lock.json
Overview
This PR delivers two major improvements to the application:
Robust Error Handling & User-Friendly Loading States: A system-wide upgrade for UX resilience during asynchronous operations.
Branch Management UI: A new interface that allows admins to efficiently manage company branches/locations and their associated resources.
✅ Features Implemented
⚠️ Robust Error Handling & Loading States
🧱 React Error Boundaries
Wrapped application in reusable ErrorBoundary component
Displays fallback UI on component-level runtime errors without crashing entire app
⏳ Loading Indicators
Added skeleton loaders and spinners for pages and components that rely on async data
Improved visual feedback for page transitions and button actions
📢 User-Friendly Error Messages
Contextual, actionable messages …
=> Implement Robust Error Handling & Loading States + Branch Management UI

backend/src/branch/branch.module.ts, backend/src/branch/controllers/branch-reporting.controller.ts, backend/src/branch/controllers/branch.controller.ts, backend/src/branch/database/migrations/001-create-branches-table.sql, backend/src/branch/decorators/branch-access.decorator.ts, backend/src/branch/dto/assign-asset.dto.ts, backend/src/branch/dto/branch-query.dto.ts, backend/src/branch/dto/branch-response.dto.ts, backend/src/branch/dto/create-branch.dto.ts, backend/src/branch/dto/update-branch.dto.ts, backend/src/branch/entities/branch.entity.ts, backend/src/branch/exceptions/branch.exceptions.ts, backend/src/branch/guards/branch-ownership.guard.ts, backend/src/branch/guards/branch.guard.ts, backend/src/branch/interfaces/branch.interface.ts, backend/src/branch/repositories/branch.repository.ts, backend/src/branch/services/branch-reporting.service.ts, backend/src/branch/services/branch-validation.service.ts, backend/src/branch/services/branch.service.ts
```typescript
import { BranchModule } from './branch/branch.module';
@Module({
imports: [
// ... other imports
BranchModule,
],
})
export class AppModule {}
```
closes #18 
```shellscript
curl -X POST http://localhost:3000/branches \
-H "Content-Type: application/json" \
-H "Authorization: Bearer YOUR_JWT_TOKEN" \
-d '{
"name": "Downtown Branch",
"address": "123 Main St",
"city": "New York",
"state": "NY",
"country": "USA",
"branchCode": "DT001",
"phone": "+1-555-0123",
"email": "downtown@company.com"
}'
```
```shellscript
curl -X GET http://localhost:3000/branches/branch-id/reports/inventory \
-H "Authorization: Bearer YOUR_JWT_TOKEN"
```
```shellscript
curl -X POST http://localhost:3000/branches/source-branch-id/assets/transfer \
-H "Content-Type: application/json" \
-H "Authorization: …
```
=> Add branch management module with access control and DTOs

backend/.gitignore, backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/certificate/certificate.controller.spec.ts, backend/src/certificate/certificate.controller.ts, backend/src/certificate/certificate.module.ts, backend/src/certificate/certificate.service.spec.ts, backend/src/certificate/certificate.service.ts, backend/src/certificate/dto/create-certificate.dto.ts, backend/src/certificate/dto/update-certificate.dto.ts, backend/src/certificate/entities/certificate.entity.ts
This PR implements the Asset Certificate module to manage high-value asset certificates. The module includes core functionality for issuance, verification, transfer tracking, and revocation.
Closes #20 
- Created `Certificate` entity with fields: `certificateId`, `asset`, `owner`, `issuedAt`, `expiresAt`, `status`, etc.
- Added relationships to `Asset` and `User` entities
- Implemented certificate issuance logic with validations and metadata
- Added verification service to check certificate validity
- Implemented ownership transfer tracking with timestamped history
- Enabled revocation with reason tracking
- Created REST APIs for interacting with the certificate system
- Integrated with the `AuditLog` module for auditing actions
=> feat: implement Asset Certificate module 

backend/.gitignore, backend/src/audit-log/audit-log.controller.spec.ts, backend/src/audit-log/audit-log.controller.ts, backend/src/audit-log/audit-log.module.ts, backend/src/audit-log/audit-log.service.spec.ts, backend/src/audit-log/audit-log.service.ts, backend/src/audit-log/dto/create-audit-log.dto.ts, backend/src/audit-log/dto/update-audit-log.dto.ts, backend/src/audit-log/entities/audit-log.entity.ts
This PR introduces a comprehensive Audit Trail module designed to log and retrieve all critical system activities for accountability, traceability, and compliance.
Closes #19
- 🧱 **AuditLog Entity**
- UUID-based ID
- `actionType` (CREATE, UPDATE, DELETE, LOGIN, LOGOUT, FAILED_LOGIN)
- `entityAffected`, `entityId`, `userId` (nullable)
- `timestamp` (auto-generated)
- `metadata` (JSON for contextual details)
- ⚙️ **AuditLogService**
- `record()` method to save new audit entries
- `getLogs()` with filters: user ID, action type, date range, pagination
- 🚪 **AuditLogController**
- Read-only `GET /audit-logs` endpoint
- Supports filtering and pagination
- 🔐 **Security & Integration**
- Ready for RBAC protection (to be applied in guards)
- Designed for easy hook/middleware integration in other …
=> feat: implement robust audit trail

frontend/app/inventory/[id]/edit/page.tsx, frontend/app/inventory/[id]/loading.tsx, frontend/app/inventory/[id]/page.tsx, frontend/app/inventory/loading.tsx, frontend/app/inventory/new/page.tsx, frontend/app/inventory/page.tsx, frontend/app/inventory/transactions/loading.tsx, frontend/app/inventory/transactions/new/page.tsx, frontend/app/inventory/transactions/page.tsx, frontend/components/inventory-form.tsx, frontend/components/transaction-form.tsx
i have just implement inventory managment ui 
close #37
=> Commit Implemention Inventory Management UI

contract/src/asset_checkout.cairo, contract/src/asset_transfer.cairo, contract/tests/test_asset_checkout.cairo, contract/tests/test_asset_transfer.cairo
=> created the checkout and transfer cairo contract with tests for each

contract/src/asset_manager.cairo, contract/src/interfaces.cairo, contract/src/inventory_registry.cairo, contract/tests/test_asset_manager.cairo, contract/tests/test_inventory_registry.cairo, contract/tests/test_runner.cairo
This pull request introduces a complete asset management smart contract system built on StarkNet, featuring multiple components for asset registration, transfer, lifecycle management, checkout, certificates, audit trail, and inventory management. The implementation includes comprehensive test suites to ensure reliability and correctness.
=> Implement Asset Management Smart Contract with Comprehensive Testing

backend/src/inventory/dto/create-inventory-item.dto.ts, backend/src/inventory/dto/inventory-response.dto.ts, backend/src/inventory/dto/stock-transaction.dto.ts, backend/src/inventory/dto/update-inventory-item.dto.ts, backend/src/inventory/entities/inventory-item.entity.ts, backend/src/inventory/entities/stock-transaction.entity.ts, backend/src/inventory/inventory.controller.ts, backend/src/inventory/inventory.module.ts, backend/src/inventory/inventory.service.ts, backend/src/inventory/repositories/stock-transaction.repository.ts, backend/src/inventory/stock-transactions.controller.ts, backend/src/inventory/stock-transactions.service.ts
This PR introduces a robust **Inventory Management module** to efficiently track consumable items within the system. It includes the following major components:
---
- **Fields**: 
- `id`, `name`, `category`, `description`, `unit_of_measurement`, `current_quantity`, `reorder_level`, `createdAt`, `updatedAt`
- **Relationships**:
- Belongs to Category (if applicable)
- One-to-many relationship with Stock Transactions
- **Fields**:
- `id`, `inventoryItemId`, `quantity`, `transactionType` (`IN` | `OUT`), `reference`, `createdAt`
- **Functionality**:
- Tracks inflow/outflow of items
- Automatically adjusts `current_quantity` on `InventoryItem`
- Triggers alert when `current_quantity <= reorder_level`
- Supports configurable alert channels:
- Email
- SMS
- Dashboard Notification
Generates key …
=> implemented the inventory module

frontend/components/home/benefits-section.tsx, frontend/components/home/cta-section.tsx, frontend/components/home/features-section.tsx, frontend/components/home/hero-section.tsx, frontend/components/home/stats-section.tsx, frontend/components/home/testimonials-section.tsx
##Description
This PR implements the Manage Assets Landing page and  all components located in the home folder. Each component is designed to be reusable and styled according to the project’s UI guidelines.
=> Created the ManageAssets Landing page

frontend/app/assets/assignments/[id]/return/page.tsx, frontend/app/assets/new/page.tsx
created and implemented the asset creation and editing forms
[#32]
=> implementation of Asset creation and ediiting forms

frontend/app/audit/asset-audit-trail.tsx, frontend/app/audit/audit-log-detail.tsx, frontend/app/audit/audit-log-list.tsx, frontend/components/audit/asset-audit-trail.tsx, frontend/components/audit/audit-log-detail.tsx, frontend/components/audit/audit-log-list.tsx
Closes issue #41
Description
This PR closes Issue #41 by introducing a user-friendly interface to display and verify audit trail logs with blockchain integration for transparency and trust.
Features Implemented
Audit Log List View
Paginated table of audit log entries
Filters for:
Date range
Event type
User
Verification status
Sorting by timestamp and relevant columns
Audit Log Detail View
Full details per log entry: event type, timestamp, user, description, and affected resources
UI controls to trigger and refresh verification
=> implement audit trail

frontend/components/notifications/notifications-dropdown.tsx, frontend/components/ui/timeline.tsx, frontend/components/ui/toast.tsx, frontend/components/ui/toaster.tsx
Implemented toast notification system. Closes #49
=> feat(ui): implemented toast notification system

backend/src/scheduled-tasks/controllers/scheduled-tasks.controller.ts, backend/src/scheduled-tasks/dto/create-scheduled-task.dto.ts, backend/src/scheduled-tasks/dto/task-execution.dto.ts, backend/src/scheduled-tasks/dto/update-scheduled-task.dto.ts, backend/src/scheduled-tasks/entities/asset.entity.ts, backend/src/scheduled-tasks/entities/inventory-item.entity.ts, backend/src/scheduled-tasks/entities/maintenance-schedule.entity.ts, backend/src/scheduled-tasks/entities/scheduled-task.entity.ts, backend/src/scheduled-tasks/entities/task-execution.entity.ts, backend/src/scheduled-tasks/scheduled-tasks.module.ts, backend/src/scheduled-tasks/services/asset-task.service.ts, backend/src/scheduled-tasks/services/inventory-task.service.ts, backend/src/scheduled-tasks/services/maintenance-task.service.ts, backend/src/scheduled-tasks/services/notification.service.ts, backend/src/scheduled-tasks/services/scheduling.service.ts, backend/src/scheduled-tasks/services/task.service.ts
Implemented the schedule task module
=> feat(logic): implemented schedule task module

backend/src/app.module.ts, backend/src/barcode/barcode.controller.ts, backend/src/barcode/barcode.entity.ts, backend/src/barcode/barcode.module.ts, backend/src/barcode/barcode.service.ts, backend/src/barcode/barcode.util.ts, backend/src/barcode/dto/generate-barcode.dto.ts
Key Features Implemented:
Barcode Generation:
Uses a barcode generation library to create barcode images in common formats (e.g., PNG, SVG).
Metadata Storage:
Saves relevant barcode metadata in the database, including code, format, and creation date.
API Endpoints:
POST /barcode: Generate a new barcode with metadata.
GET /barcode/:id: Retrieve barcode metadata and image (Base64 encoded).
File Format Support:
Supports download as PNG or SVG via future extensibility.
Mocked Independence:
Does not rely on any existing asset model; built to be self-contained and reusable.
closes #127
=> feat Barcode Generator & Registry #127

backend/src/Asset Category Module/README.md, backend/src/Asset Category Module/dbSetup.md, backend/src/Asset Category Module/src/category/category.controller.ts, backend/src/Asset Category Module/src/category/category.module.ts, backend/src/Asset Category Module/src/category/category.service.ts, backend/src/Asset Category Module/src/category/dto/category-response.dto.ts, backend/src/Asset Category Module/src/category/dto/create-category.dto.ts, backend/src/Asset Category Module/src/category/dto/update-category.dto.ts, backend/src/Asset Category Module/src/category/entities/category.entity.ts, backend/src/Asset Category Module/test/category.controller.spec.ts, backend/src/Asset Category Module/test/category.e2e-spec.ts, backend/src/Asset Category Module/test/category.service.spec.ts
=> Asset Category Module

backend/src/warranty-claims/__tests__/warranty-claims.service.spec.ts, backend/src/warranty-claims/common/decorators/file-upload.decorator.ts, backend/src/warranty-claims/dto/create-warranty-claim.dto.ts, backend/src/warranty-claims/dto/update-warranty-claim.dto.ts, backend/src/warranty-claims/dto/warranty-claim-query.dto.ts, backend/src/warranty-claims/entities/warranty-claim.entity.ts, backend/src/warranty-claims/enums/warranty-claim-status.enum.ts, backend/src/warranty-claims/warranty-claims.controller.spec.ts, backend/src/warranty-claims/warranty-claims.controller.ts, backend/src/warranty-claims/warranty-claims.e2e.spec.ts, backend/src/warranty-claims/warranty-claims.module.ts, backend/src/warranty-claims/warranty-claims.service.ts
=> warranty claims resource

backend/package-lock.json, backend/package.json, backend/src/QR-Code/entities/qrcode.entity.ts, backend/src/QR-Code/qrcode.controller.ts, backend/src/QR-Code/qrcode.module.ts, backend/src/QR-Code/qrcode.service.spec.ts, backend/src/QR-Code/qrcode.service.ts, backend/src/biometric-monitor/biometric-monitor.controller.ts, backend/src/biometric-monitor/biometric-monitor.module.ts, backend/src/biometric-monitor/biometric-monitor.service.spec.ts, backend/src/biometric-monitor/biometric-monitor.service.ts, backend/src/biometric-monitor/dto/create-device-status.dto.ts, backend/src/biometric-monitor/entities/biometric-device.entity.ts
🔍 Biometric Device Monitoring Module
✅ Summary
This PR introduces a Biometric Device Monitoring Module that operates independently and provides APIs for checking the connection and status of biometric devices through simulated/mock data. It includes endpoints to:
Register a biometric device
Update device heartbeat (i.e., simulate it being online)
Retrieve the device's last seen timestamp and uptime
Monitor online/offline status in real time
🚀 Features Implemented
Standalone Module Architecture: Fully decoupled and encapsulated logic under /biometrics/.
Entity and DB Integration:
BiometricDevice entity created with fields:
id
name
status (online/offline)
uptime
lastSeen
Mock Device Monitoring Service:
Simulates device check-in using heartbeat updates.
Tracks uptime based on last heartbeat. …
=> Biometric device monitor

backend/Audit-Log/audit-log.controller.ts, backend/Audit-Log/audit-log.module.ts, backend/Audit-Log/audit-log.service.ts, backend/Audit-Log/dto/create-audit-log.dto.ts, backend/Audit-Log/entities/audit-log.entity.ts, backend/Audit-Log/tests/audit-log.service.spec.ts, backend/package-lock.json, backend/package.json, backend/readme.md, backend/src/QR-Code/entities/qrcode.entity.ts, backend/src/QR-Code/qrcode.controller.ts, backend/src/QR-Code/qrcode.module.ts, backend/src/QR-Code/qrcode.service.spec.ts, backend/src/QR-Code/qrcode.service.ts, backend/src/biometric-monitor/biometric-monitor.controller.ts, backend/src/biometric-monitor/biometric-monitor.module.ts, backend/src/biometric-monitor/biometric-monitor.service.spec.ts, backend/src/biometric-monitor/biometric-monitor.service.ts, backend/src/biometric-monitor/dto/create-device-status.dto.ts, backend/src/biometric-monitor/entities/biometric-device.entity.ts
implemented  and Created a system-wide audit trail to log admin actions like updates to settings, role changes, or deletions. Store entries in an audit_logs table. as a full module. also wrote test
=> Audit trail

backend/Audit-Log/audit-log.controller.ts, backend/Audit-Log/audit-log.module.ts, backend/Audit-Log/audit-log.service.ts, backend/Audit-Log/dto/create-audit-log.dto.ts, backend/Audit-Log/entities/audit-log.entity.ts, backend/Audit-Log/tests/audit-log.service.spec.ts, backend/package-lock.json, backend/package.json, backend/readme.md, backend/src/QR-Code/entities/qrcode.entity.ts, backend/src/QR-Code/qrcode.controller.ts, backend/src/QR-Code/qrcode.module.ts, backend/src/QR-Code/qrcode.service.spec.ts, backend/src/QR-Code/qrcode.service.ts, backend/src/biometric-monitor/biometric-monitor.controller.ts, backend/src/biometric-monitor/biometric-monitor.module.ts, backend/src/biometric-monitor/biometric-monitor.service.spec.ts, backend/src/biometric-monitor/biometric-monitor.service.ts, backend/src/biometric-monitor/dto/create-device-status.dto.ts, backend/src/biometric-monitor/entities/biometric-device.entity.ts, backend/src/notifications/dto/create-notification.dto.ts, backend/src/notifications/dto/update-notification.dto.ts, backend/src/notifications/entities/notification.entity.ts, backend/src/notifications/notifications.controller.ts, backend/src/notifications/notifications.module.ts, backend/src/notifications/notifications.service.spec.ts, backend/src/notifications/notifications.service.ts
i implemented a standalone module for sending and storing notifications for users. This module  includes a database schema for storing messages, sender, receiver, read status, and timestamps. It s expose endpoints to create notifications, mark as read, and fetch by user. This module is now built to function independently and must not rely on any other module within the system.
=> Notifications system

backend/src/tagging/controllers/tag.controller.spec.ts, backend/src/tagging/dto/bulk-assign-tags.dto.ts, backend/src/tagging/dto/create-tag.dto.ts, backend/src/tagging/dto/query-tags.dto.ts, backend/src/tagging/dto/update-tag.dto.ts, backend/src/tagging/entities/agged-resource.entity.ts, backend/src/tagging/entities/tag.entity.ts, backend/src/tagging/migrations/1234567890-create-tagging-tables.ts, backend/src/tagging/services/tag.service.spec.ts, backend/src/tagging/services/tag.service.ts, backend/src/tagging/tagging.module.ts, backend/src/tagging/test/tagging.e2e-spec.ts
=> Asset tagging module

backend/src/app.module.ts, backend/src/mobile-devices/README.md, backend/src/mobile-devices/dto/create-mobile-device.dto.ts, backend/src/mobile-devices/dto/query-mobile-device.dto.ts, backend/src/mobile-devices/dto/update-mobile-device.dto.ts, backend/src/mobile-devices/entities/mobile-device.entity.ts, backend/src/mobile-devices/mobile-devices.controller.ts, backend/src/mobile-devices/mobile-devices.e2e-spec.ts, backend/src/mobile-devices/mobile-devices.module.ts, backend/src/mobile-devices/mobile-devices.service.spec.ts, backend/src/mobile-devices/mobile-devices.service.ts
=> Feat mobile inventory

backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/compliance/compliance.controller.ts, backend/src/compliance/compliance.entity.ts, backend/src/compliance/compliance.scheduler.ts, backend/src/compliance/compliance.service.ts, backend/src/compliance/dto/create-compliance.dto.ts
=> Regulatory Compliance Tracker Module

backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/jobs/dynamic-jobs.service.ts, backend/src/jobs/interfaces/job-definition.interface.ts, backend/src/jobs/job.service.ts, backend/src/jobs/jobs.controller.ts, backend/src/jobs/jobs.module.ts
📝 Pull Request Description
This PR introduces the Scheduled Jobs Module (#136), enabling cron-based task execution using @nestjs/schedule. Key features include:
✅ Features Implemented:
Integrated @nestjs/schedule and configured a sample cron job
Created JobDefinition interface to support dynamic job registration
Implemented DynamicJobsService to manage jobs at runtime
Added structured logging for job executions with timestamps and error tracking
Developed REST endpoints:
POST /jobs/register to register new jobs
POST /jobs/disable/:name and POST /jobs/enable/:name to toggle jobs
GET /jobs to list active job names
🔒 Assumptions:
Jobs are stored in-memory (non-persistent)
Registered handlers are provided at runtime; future support for job templates possible
📌 Closing
closes #136
=> Feature: Dynamic Scheduled Jobs Module with Cron Support (#136)

backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/device-health/device-health.controller.spec.ts, backend/src/device-health/device-health.controller.ts, backend/src/device-health/device-health.module.ts, backend/src/device-health/device-health.service.spec.ts, backend/src/device-health/device-health.service.ts, backend/src/device-health/dto/create-device-health.dto.ts, backend/src/device-health/dto/update-device-health.dto.ts, backend/src/device-health/entities/device-health.entity.ts
Available API Endpoints:
GET /device-health - Get all health records with filtering/pagination
GET /device-health/latest - Get latest health status for all devices
GET /device-health/stats - Get health statistics overview
GET /device-health/device/:deviceId/latest - Get latest health for specific device
GET /device-health/devices - Get list of all monitored devices
GET /device-health/alerts - Get devices with warning/critical/offline status
POST /device-health - Create new health record manually
POST /device-health/simulate - Manually trigger health simulation
Key Features:
Automatic Simulation: Runs every 5 minutes via cron job
Realistic Data: Generates temperature, CPU, memory, disk
closes #145
=> health check feature added

backend/Audit-Log/audit-log.controller.ts, backend/Audit-Log/audit-log.service.ts, backend/Audit-Log/entities/audit-log.entity.ts, backend/src/app.module.ts, backend/src/warranty/dto/create-warranty.dto.ts, backend/src/warranty/dto/update-warranty.dto.ts, backend/src/warranty/entities/warranty.entity.ts, backend/src/warranty/warranty.controller.ts, backend/src/warranty/warranty.module.ts, backend/src/warranty/warranty.service.ts
- Created WarrantyModule with service, controller, and PostgreSQL entity
- Added endpoints to manage warranties independently of asset module
- Implemented mock expiry notifications using setTimeout
- Handles warranty terms, expiry date, and duration per asset
=> feat(warranty): implement warranty module with CRUD operations and expiry alerts

backend/.env.example, backend/package-lock.json, backend/package.json, backend/src/QR-Code/qrcode.controller.ts, backend/src/QR-Code/qrcode.service.ts, backend/src/app.module.ts
The QR code module is registered in app.module.ts.
The /qrcode/:id endpoint returns a QR code image (PNG or SVG) with asset info and a link, using only its own data.
The implementation is self-contained and does not depend on the asset module.
The code is clean and ready for use.
=> qr code generation generation

backend/src/api-keys/README.md, backend/src/api-keys/api-keys.controller.spec.ts, backend/src/api-keys/api-keys.controller.ts, backend/src/api-keys/api-keys.e2e-spec.ts, backend/src/api-keys/api-keys.module.ts, backend/src/api-keys/api-keys.service.spec.ts, backend/src/api-keys/api-keys.service.ts, backend/src/api-keys/decorators/api-key-scopes.decorator.ts, backend/src/api-keys/dto/api-key-response.dto.ts, backend/src/api-keys/dto/create-api-key.dto.ts, backend/src/api-keys/dto/query-api-keys.dto.ts, backend/src/api-keys/dto/revoke-api-key.dto.ts, backend/src/api-keys/dto/update-api-key.dto.ts, backend/src/api-keys/entities/api-key.entity.ts, backend/src/api-keys/examples/assets-controller-example.ts, backend/src/api-keys/guards/api-key-auth.guard.ts, backend/src/api-keys/guards/api-key-scopes.guard.spec.ts, backend/src/api-keys/guards/api-key-scopes.guard.ts, backend/src/api-keys/guards/jwt-or-api-key-auth.guard.ts, backend/src/api-keys/strategies/api-key.strategy.spec.ts, backend/src/api-keys/strategies/api-key.strategy.ts, backend/src/app.module.ts
The Api Management module has been successfully created and implemented accordingly.
=> Created and implemented Api management

backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/transfer/dto/create-transfer-request.dto.ts, backend/src/transfer/dto/query-transfer-request.dto.ts, backend/src/transfer/dto/update-transfer-request.dto.ts, backend/src/transfer/enums/transfer-status.enum.ts, backend/src/transfer/transfer-request.entity.ts, backend/src/transfer/transfer.controller.spec.ts, backend/src/transfer/transfer.controller.ts, backend/src/transfer/transfer.module.ts, backend/src/transfer/transfer.service.spec.ts, backend/src/transfer/transfer.service.ts
This PR introduces a standalone **Asset Transfer Module** to handle and track transfers between departments, users, or locations.  
The module is independent and only references assets using their `assetId`.
closses issue #105 
- **TransferRequest Entity** with fields:
- assetId
- requestedBy
- fromLocation
- toLocation
- status (Initiated, In Transit, Delivered, Cancelled)
- approvalDate
- reason
- **CRUD Endpoints**
- Create new transfer request
- Update transfer status/details
- Fetch transfer requests
- **Query Filtering**
- Filter transfers by destination, requester, and status
- **Testing**
- Unit tests for services and controllers
- E2E tests to validate the transfer lifecycle
=> feat(transfer): standalone asset transfer module with tracking and filtering

backend/src/modules/contracts/contract.entity.ts, backend/src/modules/contracts/contracts.controller.ts, backend/src/modules/contracts/contracts.service.ts, backend/src/modules/contracts/dto/create-contract.dto.ts, backend/src/modules/contracts/dto/update-contract.dto.ts, backend/src/modules/contracts/enums/contract-status.enum.ts, backend/src/modules/dto/create-warranty.dto.ts, backend/src/modules/dto/extend-warranty.dto.ts, backend/src/modules/dto/update-warranty.dto.ts, backend/src/modules/warranty/warranty.controller.ts, backend/src/modules/warranty/warranty.entity.ts, backend/src/modules/warranty/warranty.module.ts, backend/src/modules/warranty/warranty.repository.ts, backend/src/modules/warranty/warranty.service.ts, backend/src/test/contracts/contracts.controller.spec.ts, backend/src/test/contracts/contracts.e2e-spec.ts, backend/src/test/contracts/contracts.service.spec.ts, package-lock.json, package.json
This PR introduces a new **Contract Management Module** (#115) to handle vendor and third-party contracts for assets and services. The system provides full contract lifecycle management including creation, updating, retrieval, deletion, and validation.
- Contract entity with fields: `contractId`, `vendorId`, `title`, `terms`, `startDate`, `endDate`, `documentUrl`, `status`
- Status tracking (`Active`, `Expired`, `Terminated`, `Pending`)
- Endpoints for CRUD operations
- File upload support for PDF contract documents
- Filtering for expired or active contracts
- Validation logic to block overlapping contracts per vendor
- Unit tests with full coverage
- File uploads currently support mocked or real PDF storage.
- Overlapping contract validation ensures data integrity at the vendor level. …
=> Add Contract Management Module #115

backend/src/app.module.ts, backend/src/sla-management/dto/create-sla-breach.dto.ts, backend/src/sla-management/dto/create-sla-record.dto.ts, backend/src/sla-management/dto/sla-query.dto.ts, backend/src/sla-management/dto/update-sla-record.dto.ts, backend/src/sla-management/entities/sla-breach.entity.ts, backend/src/sla-management/entities/sla-record.entity.ts, backend/src/sla-management/sla.controller.ts, backend/src/sla-management/sla.enums.ts, backend/src/sla-management/sla.module.ts, backend/src/sla-management/sla.service.ts, backend/src/sla-management/tests/sla.controller.spec.ts, backend/src/sla-management/tests/sla.integration.spec.ts, backend/src/sla-management/tests/sla.service.spec.ts
Implement SLA Management Module with Full CRUD, Monitoring, and Breach Tracking
---
This PR introduces a fully-featured **Service Level Agreement (SLA) management module** with robust professional features, including automated monitoring, breach tracking, and advanced filtering. The module is fully integrated into `app.module.ts` and follows existing project architecture patterns.
---
* **SLARecord Entity:**
Includes `vendorId`, `serviceDescription`, `coverageStart`, `coverageEnd`, `assetCategory`, `breachPolicy`, plus professional fields like `priority`, `responseTimes`, and `uptimeTracking`.
* **SLABreach Entity:**
Tracks violations with severity levels and resolution tracking.
* **CRUD API Endpoints:**
* `POST /sla` – Create SLA record
* `GET /sla` – List SLAs with filtering & …
=> Service Level Agreement

backend/src/app.module.ts, backend/src/insurance-tracker/dto/create-insurance-policy.dto.ts, backend/src/insurance-tracker/dto/insurance-query.dto.ts, backend/src/insurance-tracker/dto/update-insurance-policy.dto.ts, backend/src/insurance-tracker/dto/upload-document.dto.ts, backend/src/insurance-tracker/entities/insurance-policy.entity.ts, backend/src/insurance-tracker/entities/policy-document.entity.ts, backend/src/insurance-tracker/insurance.controller.ts, backend/src/insurance-tracker/insurance.enums.ts, backend/src/insurance-tracker/insurance.module.ts, backend/src/insurance-tracker/insurance.service.ts, backend/src/insurance-tracker/tests/insurance.controller.spec.ts, backend/src/insurance-tracker/tests/insurance.integration.spec.ts, backend/src/insurance-tracker/tests/insurance.service.spec.ts, backend/src/sla-management/dto/create-sla-breach.dto.ts, backend/src/sla-management/dto/create-sla-record.dto.ts, backend/src/sla-management/dto/sla-query.dto.ts, backend/src/sla-management/dto/update-sla-record.dto.ts, backend/src/sla-management/entities/sla-breach.entity.ts, backend/src/sla-management/entities/sla-record.entity.ts, backend/src/sla-management/sla.controller.ts, backend/src/sla-management/sla.enums.ts, backend/src/sla-management/sla.module.ts, backend/src/sla-management/sla.service.ts, backend/src/sla-management/tests/sla.controller.spec.ts, backend/src/sla-management/tests/sla.integration.spec.ts, backend/src/sla-management/tests/sla.service.spec.ts
Implement Comprehensive Insurance Management Module with CRUD, Monitoring, and File Handling
---
This PR introduces a full-featured **Insurance Management Module** designed for professional, enterprise-grade tracking of insurance policies, documents, and automated monitoring. The module is fully integrated into `app.module.ts`, leverages `MulterModule` for secure file uploads, and follows existing project architecture patterns.
---
* **InsurancePolicy Entity:**
Includes `policyNumber`, `provider`, `assetId` / `assetCategory`, `coverageStart`, `coverageEnd`, `insuredValue`, `termsUrl`, `status`, plus professional fields like premium tracking, deductibles, and contact management.
* **PolicyDocument Entity:**
Secure file management with upload/download capabilities and type/size validation. …
=> Insurance tracker module

contracts/Cargo.lock, contracts/Cargo.toml, contracts/assetsup_contract/Cargo.toml, contracts/assetsup_contract/src/lib.rs, contracts/assetsup_contract/src/tests/initialize.rs, contracts/assetsup_contract/src/tests/mod.rs, contracts/assetsup_contract/test_snapshots/tests/initialize/test_initialize.1.json, contracts/assetsup_contract/test_snapshots/tests/initialize/test_initialize_panic.1.json
=> Create Stellar Soroban Contract Folder and Implement Basic Scaffolding 

frontend/components/ui/Pagination.tsx
=> Fix: Add Basic Pagination Component
